### ISSUE TITLE
Android wifi print

### ISSUE THREAD

**Issue by karthikeyanappdev** [SureshCS-50/Android-wifi-print#1]
Hi, its not working after selecting printer device. Its working project?

**Comment by SureshCS-50** [comment]
can you tell me how you used this.. and can you explain clearly, what is your requirement?

**Comment by karthikeyanappdev** [comment]
Hi Suresh,
                Regarding android wifi print, its working after page count
printer dialog should displayed, how to display all printer list. pls
 explain it


Regards,
Karthikeyan.S
+917200785809

**Comment by SureshCS-50** [comment]
As far as I explored, I can't able to differentiate WIFI routers and Printers from the list.
There are some minor issue in this prototype am working on this, will update.

**Comment by SureshCS-50** [comment]
Thanks :)
